# Generated by Django 2.0 on 2017-08-31 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
        ('hello', '0003_blog_blog_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog_author',
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='first.Author'),
            preserve_default=False,
        ),
    ]
