# Generated by Django 2.0 on 2017-08-31 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20170831_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tag',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
