# Generated by Django 2.0 on 2017-09-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_blog_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='DATE CREATED')),
                ('way', models.CharField(max_length=32)),
                ('strength', models.CharField(max_length=64)),
            ],
        ),
    ]
